### PR TITLE
Integration: JustSend.pl Driver

### PR DESCRIPTION
**Pull request by kduma**
An SMS driver to justsend.pl sms sending website

### CODE REVIEW

**Comment by secrethash** [comment]
Thanks, Working on it. Testing the Integration.

**Comment by secrethash** [comment]
Isn't there any english version of the website? I would really love to added the provider.

**Comment by kduma** [comment]
Nope. It is polish only website.

**Comment by secrethash** [comment]
I can't Understand Polish. Unable to read the **API Documentation**. 😕

**Comment by kduma** [comment]
Docs are here: https://justsend.pl/api-dokumentacja/ 
(it's in polish so you would need google translate to read it 😃)

To send SMS message we're intrested in point 3.6. from docs. The endpoint for sending messages is: `https://justsend.pl/api/rest/message/send/{appKey}`. To send a message we need to post json in this format:
```
{
 "message": "",
 "from": "",
 "bulkVariant": "",
 "to": ""
}
```
where:
- `message` & `to` fields are self explanatiory
- `bulkVariant`: is message type - can be `ECO`, `FULL` or `PRO` - explained bellow
- `from`: when `bulkVariant` is `FULL` or `PRO` we can pass a string which will be displayed as _from_ number on user device.

Bulk Variants:

`bulkVariant` | `from` field | user gets message from
------------- | ------------- | ---------------
ECO | _not used_ | random number
FULL | can be one of this: INFO, INFORMACJA, KONKURS, NOWOSC, OFERTA, OKAZJA, PROMOCJA, SMS | sender will be specified as in `from` field
PRO | can be any string with length up to 11 characters, and no more than 2 numbers side by side | sender will be specified as in `from` field

To visualise the diffrence between them, I will give you examples:

Example 1:
```php
SMSG::send('+48123456789', 'ECO', 'I\'m testing the ECO BulkVersion.');
```
img_0085
img_0086

Example 2:
```php
SMSG::send('+48123456789', 'TESTSMSG', 'I\'m testing the PRO BulkVersion with TESTSMSG string as from address.');
```
img_0087
img_0088

**Comment by secrethash** [comment]
This explains the basic Documentation that I needed for testing.. Thanks a lot..

**Pull request closed without merging**
